name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  fpdart: ^0.1.0
  bcrypt: ^1.1.3
  string_validator: ^0.3.0
  jose: ^0.3.2
  meta: ^1.8.0
  path: ^1.8.0
  postgres: ^2.4.5
  redis_dart: ^0.1.0+4
  shelf: ^1.3.1
  shelf_modular: ^2.0.0-dev.3
  shelf_multipart: ^1.0.0
  uuid: ^3.0.6
  mime: ^1.0.2
  http_parser: ^4.0.1
  dart_jsonwebtoken: ^2.4.1
  shelf_swagger_ui: ^1.0.0+2


dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
