openapi: 3.0.0
info:
  description: "API sistema de gerenciamento de desenvolvedores da FTeam"
  version: "1.0.10"
  title: "Swagger Ship"
servers:
  - url: https://dev.shipstore.info
    description: Developer server
  - url: http://localhost:4000
    description: Local server
tags:
- name: "auth"
  description: "Autorização de usuário"
- name: "user"
  description: "Access to User"
- name: "file"
  description: "Upload e Download de arquivos"
- name: "project"
  description: "Access to project"
- name: "user-on-project"
  description: "many-to-many User -> Project"
paths:
  /auth/login:
    get:
      security:
        - basicAuth: [] 
      tags:
        - "auth"
      responses:
        '200':   
          description: Realizado login com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokenization"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /auth/check_token:
    get:
      security:
        - bearerAuth: [] 
      tags:
        - "auth"
      responses:
        '200':   
          description: Checa autorização
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: string
  /auth/update_password:
    put:
      security:
        - bearerAuth: [] 
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':   
          description: Checa autorização
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: string
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /auth/refresh_token:
    get:
      tags:
        - "auth"
      security:
        - bearerAuthRefreshToken: [] 
      responses:
        '200':   
          description: Atualiza token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokenization" 
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'         
  /file/upload:
    post:
      tags:
      - "file"
      security:
        - bearerAuth: [] 
      summary: "Upload de um arquivo"
      description: ""
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileReturn"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /file/download/{file}:
    get:
      tags:
      - "file"
      summary: "Download file"
      description: ""
      operationId: "donwloadFile"
      parameters:
      - name: "file"
        in: "path"
        description: "file name"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            image/jpg:
              schema:
                type: string
                format: binary

  /user/{id}:
    get:
      tags:
      - "user"
      security:
        - bearerAuth: [] 
      summary: "get user by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /user:
    get:
      tags:
      - "user"
      security:
        - bearerAuth: [] 
      summary: "get all user"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    post:
      tags:
      - "user"
      security:
        - bearerAuth: [] 
      summary: "Create a use"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
              
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    put:
      tags:
      - "user"
      security:
        - bearerAuth: [] 
      summary: "Update a use"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
              
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /project/{id}:
    get:
      tags:
      - "project"
      security:
        - bearerAuth: [] 
      summary: "get project by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The project ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /project:
    get:
      tags:
      - "project"
      security:
        - bearerAuth: [] 
      summary: "get all project"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProjectEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    post:
      tags:
      - "project"
      security:
        - bearerAuth: [] 
      summary: "Create a project"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectEntity"
              
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    put:
      tags:
      - "project"
      security:
        - bearerAuth: [] 
      summary: "Update a project"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectEntity"
              
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /userOnProject/usersByProjectId/{projectId}:
    get:
      tags:
      - "user-on-project"
      security:
        - bearerAuth: [] 
      
      summary: "get users by project id"
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The project ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /userOnProject/projectsByUserId/{userId}:
    get:
      tags:
      - "user-on-project"
      security:
        - bearerAuth: [] 
      
      summary: "get users by project id"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEntity"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
   
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Auth header (Authorization) Access Token"
    bearerAuthRefreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "(Authorization) Refresh Token"
    basicAuth:   
      type: http
      scheme: basic
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    Unauthorized:
      description: Forbidden operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
  schemas:
    ErrorEntity:
      type: "object"
      properties:
        error:
          type: string
    FileReturn:
      type: "object"
      properties:
        image:
          type: string
    Tokenization:
      type: "object"
      properties:
        expiresIn:
          type: integer
        accessToken:
          type: string
        refreshToken:
          type: string
    UserEntity:
      type: "object"
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        imageUrl:
          type: string
        active:
          type: boolean
        role:
          type: string
          default: "user"
          enum:
            - "dev"
            - "manager"
            - "admin"
    ProjectEntity:
      type: "object"
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        active:
          type: boolean


