openapi: 3.0.0
info:
  description: "API sistema de gerenciamento de desenvolvedores da FTeam"
  version: "1.0.10"
  title: "Swagger Ship"
servers:
  - url: https://dev.shipstore.info
    description: Developer server
  - url: http://localhost:4000
    description: Local server
tags:
- name: "auth"
  description: "Autorização de usuário"
- name: "user"
  description: "Access to User"
- name: "file"
  description: "Upload e Download de arquivos"
- name: "project"
  description: "Access to project"
- name: "user-on-project"
  description: "many-to-many | User -> Project"
paths:
  # auth
  /auth/login:
    $ref: ./src/auth.yaml#/components/login
  /auth/check_token:
    $ref: ./src/auth.yaml#/components/check_token
  /auth/update_password:
    $ref: ./src/auth.yaml#/components/update_password
  /auth/refresh_token:
    $ref: ./src/auth.yaml#/components/refresh_token

  # upload   
  /file/upload:
    $ref: ./src/file.yaml#/components/upload
  /file/{file}:
    $ref: ./src/file.yaml#/components/download

  # user
  /logged_user:
    $ref: ./src/user.yaml#/components/loggedUser
  /user/{id}:
    $ref: ./src/user.yaml#/components/userById
  /user:
    $ref: ./src/user.yaml#/components/userCrud
  
  # project
  /project/{id}:
    $ref: ./src/project.yaml#/components/projectById
  /project:
    $ref: ./src/project.yaml#/components/projectCrud

  # userOnProject
  /userOnProject/usersByProjectId/{projectId}:
    $ref: ./src/user_on_project.yaml#/components/usersByProjectId
  /userOnProject/projectsByUserId/{userId}:
    $ref: ./src/user_on_project.yaml#/components/projectsByUserId
    

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Auth header (Authorization) Access Token"
    bearerAuthRefreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "(Authorization) Refresh Token"
    basicAuth:   
      type: http
      scheme: basic
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    Unauthorized:
      description: Forbidden operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
  schemas:
    ErrorEntity:
      type: "object"
      properties:
        error:
          type: string
    UserEntity:
      $ref: "./src/user.yaml#/components/schemas/UserEntity"
    ProjectEntity:
      $ref: "./src/project.yaml#/components/schemas/ProjectEntity"
